homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/json/

config:
conversation:
frontend:
  themes: !include_dir_merge_named themes/
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
system_health:
my:

# updater:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # ssl_certificate: !secret ssl_certificate
  # ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret trusted_proxy_ip_cf
#  ip_ban_enabled: true
#  login_attempts_threshold: 3

recorder:
  purge_keep_days: 5
#  db_url: !secret recorder_db_url

history:

logbook:
  include:
    domains:
      - automation
      - cover
      - device_tracker
      - logbook
      - script
      - switch

lovelace:
  mode: storage
  dashboards:
    lovelace-dashboard:
      mode: yaml
      filename: ui-dashboard.yaml
      title: Dashboard
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      require_admin: false


influxdb:
  exclude:
    entity_globs: "*"

sun:

energy:
utility_meter:
  grid_consumption_hourly:
    source: sensor.energy_usage_kwh
    name: Grid Consumption - Hourly
    cycle: hourly
    tariffs:
      - peak
      - offpeak
  grid_consumption_daily:
    source: sensor.energy_usage_kwh
    name: Grid Consumption - Daily
    cycle: daily
    tariffs:
      - peak
      - offpeak
  grid_consumption_monthly:
    source: sensor.energy_usage_kwh
    name: Grid Consumption - Monthly
    cycle: monthly
    tariffs:
      - peak
      - offpeak

alexa:
  smart_home:
    locale: en-US



    filter:
      include_entities:
        - fan.bathroom_fan
        - input_boolean.mode_guest
        - input_boolean.mode_home_theater
        - input_boolean.mode_sleep
        - input_boolean.mode_stranger_danger
        - media_player.living_room_apple_tv
        - media_player.rec_room_apple_tv
        - script.scene_bedroom_alarm_dismissed
        - script.scene_bedroom_tiles_wakeup
        - script.scene_bedroom_neutral_low
      include_domains:
        - light
      exclude_entities:
        - light.bedroom_1
        - light.bedroom_2
        - light.bedroom_switch
        - light.den_1
        - light.den_2
        - light.den_cabinet_1
        - light.den_cabinet_2
        - light.den_dimmer
        - light.downstairs_patio_1
        - light.downstairs_patio_2
        - light.downstairs_patio_3
        - light.downstairs_patio_dimmer
        - light.garage_motion_basic
        - light.upstairs_patio_1
        - light.upstairs_patio_2
        - light.upstairs_patio_dimmer
        - light.upstairs_patio_outlet
        - light.studio_1
        - light.studio_2
      exclude_entity_globs:
        - light.*_basic
    entity_config:
      script.scene_bedroom_alarm_dismissed:
        display_categories: SWITCH

homekit:
  - filter:
      include_domains:
        - climate
        - light
      include_entities:
        - binary_sensor.bedroom_windows
        - binary_sensor.den_door
        - binary_sensor.den_windows
        - binary_sensor.front_door
        - binary_sensor.front_door_doorbell
        - binary_sensor.garage_door
        - binary_sensor.studio_windows
        - binary_sensor.kitchen_windows
        - binary_sensor.living_room_windows
        - binary_sensor.patio_door
        - binary_sensor.rec_room_windows
        - binary_sensor.den_multisensor_sensor
        - binary_sensor.bedroom_closet_trisensor_sensor
        - binary_sensor.downstairs_hallway_trisensor_sensor
        - binary_sensor.front_door_motion
        - binary_sensor.garage_motion_sensor
        - binary_sensor.garage_stairs_multisensor_sensor
        - binary_sensor.living_room_motion_sensor
        - binary_sensor.main_stairs_multisensor_sensor
        - binary_sensor.upstairs_hallway_motion_sensor
        - fan.bedroom
        - fan.kitchen
        - input_boolean.mode_guest
        - input_boolean.mode_home_theater
        - input_boolean.mode_sleep
        - remote.living_room_apple_tv
        - sensor.bedroom_nitrogen_dioxide
        - sensor.bedroom_pm_10
        - sensor.bedroom_pm_2_5
        - sensor.bedroom_volatile_organic_compounds
        - sensor.kitchen_nitrogen_dioxide
        - sensor.kitchen_pm_10
        - sensor.kitchen_pm_2_5
        - sensor.kitchen_volatile_organic_compounds
        - sensor.downstairs_thermostat_humidity
        - sensor.upstairs_thermostat_humidity
      exclude_entities:
        - light.patio
        - light.patio_string
        - light.downstairs_patio
        - light.den
        - light.den_cabinets
        - light.bedroom
        - light.upstairs_hallway_group
        - light.upstairs_patio
        - light.studio
      exclude_entity_globs:
        - light.*_basic
  - name: Front Door Camera
    port: 51065
    mode: accessory
    filter:
      include_entities:
        - camera.front_door_high_resolution_channel
    entity_config:
      camera.front_door_high_resolution_channel:
        support_audio: true
        linked_doorbell_sensor: binary_sensor.front_door_doorbell
        linked_motion_sensor: binary_sensor.front_door_motion
  - name: Downstairs Hallway Camera
    port: 51027
    mode: accessory
    filter:
      include_entities:
        - camera.downstairs_hallway_high_resolution_channel
    entity_config:
      camera.downstairs_hallway_high_resolution_channel:
        linked_motion_sensor: binary_sensor.downstairs_hallway_motion
  - name: Main Floor Hallway Camera
    port: 51076
    mode: accessory
    filter:
      include_entities:
        - camera.main_floor_high_resolution_channel
    entity_config:
      camera.main_floor_high_resolution_channel:
        linked_motion_sensor: binary_sensor.main_floor_motion
  - name: Main Patio Camera
    port: 51023
    mode: accessory
    filter:
      include_entities:
        - camera.main_patio_high_resolution_channel
    entity_config:
      camera.main_patio_high_resolution_channel:
        linked_motion_sensor: binary_sensor.main_patio_motion
  - name: Garage Camera
    port: 51097
    mode: accessory
    filter:
      include_entities:
        - camera.garage_high_resolution_channel
    entity_config:
      camera.garage_high_resolution_channel:
        linked_motion_sensor: binary_sensor.garage_motion
  - name: Front Door Lock
    port: 51742
    mode: accessory
    filter:
      include_entities:
        - lock.august_web_front_door
  - name: Garage Door Lock
    port: 51134
    mode: accessory
    filter:
      include_entities:
        - lock.august_web_garage_door
  - name: Garage Actual
    port: 51876
    mode: accessory
    filter:
      include_entities:
        - cover.garage_actual

mobile_app:

# Disabled Features ##########################################
# introduction:
# discovery:
# ssdp:
# zeroconf:
# tts:
#   platform: google

# Includes ###################################################
# automation: !include_dir_merge_list automation/
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
group: !include group.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
media_player: !include media_player.yaml
rest_command: !include rest_command.yaml
scene: !include scene.yaml
# script: !include_dir_merge_named script/
script: !include scripts.yaml
sensor: !include sensor.yaml
shell_command: !include shell_command.yaml
template: !include_dir_merge_list template/

# Notification Groups
notify:
  - name: all_devices
    platform: group
    services:
      - action: mobile_app_alexis_iphone
      - action: mobile_app_alexis_ipad_mini
