# PMS Statistics
# Seems to be a perfomance hit
# - platform: plex
#   host: !secret pms_host
#   port: !secret pms_port
#   name: !secret pms_name
#   username: !secret plex_username
#   password: !secret plex_password
#   server: !secret pms_server

# Time & Date
- platform: time_date
  display_options:
    - time
    - date

- platform: integration
  source: sensor.energy_usage
  name: Energy Usage kWh
  unit_prefix: k
  round: 2

- platform: rest
  name: Tautulli Plex Update Available
  resource: !secret tautulli_plex_update
  json_attributes_path: "$.response.data"
  json_attributes:
    - version
  value_template: '{{ "on" if value_json.response.data.update_available else "off" }}'
  scan_interval: 3600

# InfluxDB Sensors
- platform: influxdb
  host: !secret influxdb_host
  port: !secret influxdb_port
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    # Woodhouse Server
    - name: Woodhouse CPU Load 1
      unit_of_measurement: "1 min"
      group_function: last
      where: '"host" = ''woodhouse'' and time > now() - 5m'
      value_template: "{{ value | round(2) }}"
      measurement: '"system"'
      field: '"load1"'
      database: server_metrics
    - name: Woodhouse CPU Load 5
      unit_of_measurement: "5 min"
      group_function: last
      where: '"host" = ''woodhouse'' and time > now() - 5m'
      value_template: "{{ value | round(2) }}"
      measurement: '"system"'
      field: '"load5"'
      database: server_metrics
    - name: Woodhouse CPU Load 15
      unit_of_measurement: "15 min"
      group_function: last
      where: '"host" = ''woodhouse'' and time > now() - 5m'
      value_template: "{{ value | round(2) }}"
      measurement: '"system"'
      field: '"load15"'
      database: server_metrics
    - name: Woodhouse CPU1 Temp
      unit_of_measurement: "ºC"
      group_function: last
      where: '"host" = ''woodhouse'' and "chip" = ''coretemp-isa-0000'' and time > now() - 5m'
      value_template: "{{ value | round() }}"
      measurement: '"sensors"'
      field: '"temp_input"'
      database: server_metrics
    - name: Woodhouse CPU2 Temp
      unit_of_measurement: "ºC"
      group_function: last
      where: '"host" = ''woodhouse'' and "chip" = ''coretemp-isa-0001'' and time > now() - 5m'
      value_template: "{{ value | round() }}"
      measurement: '"sensors"'
      field: '"temp_input"'
      database: server_metrics
    - name: Woodhouse RAM Used
      unit_of_measurement: "%"
      group_function: last
      where: '"host" = ''woodhouse'' and time > now() - 5m'
      value_template: "{{ value | round() }}"
      measurement: '"mem"'
      field: '"used_percent"'
      database: server_metrics
    - name: Woodhouse Disk Used
      unit_of_measurement: "%"
      group_function: last
      where: '"host" = ''woodhouse'' and time > now() - 5m'
      value_template: "{{ value | round() }}"
      measurement: '"disk"'
      field: '"used_percent"'
      database: server_metrics
    # Black Pearl Server
    - name: Black Pearl CPU Load 1
      unit_of_measurement: "1 min"
      group_function: last
      where: '"host" = ''blackpearl'' and time > now() - 5m'
      value_template: "{{ value | round(2) }}"
      measurement: '"system"'
      field: '"load1"'
      database: server_metrics
    - name: Black Pearl CPU Load 5
      unit_of_measurement: "5 min"
      group_function: last
      where: '"host" = ''blackpearl'' and time > now() - 5m'
      value_template: "{{ value | round(2) }}"
      measurement: '"system"'
      field: '"load5"'
      database: server_metrics
    - name: Black Pearl CPU Load 15
      unit_of_measurement: "15 min"
      group_function: last
      where: '"host" = ''blackpearl'' and time > now() - 5m'
      value_template: "{{ value | round(2) }}"
      measurement: '"system"'
      field: '"load15"'
      database: server_metrics
    - name: Black Pearl CPU Temp
      unit_of_measurement: "ºC"
      group_function: last
      where: '"host" = ''blackpearl'' and "chip" = ''cpu_thermal-virtual-0'' and time > now() - 5m'
      value_template: "{{ value | round() }}"
      measurement: '"sensors"'
      field: '"temp_input"'
      database: server_metrics
    - name: Black Pearl RAM Used
      unit_of_measurement: "%"
      group_function: last
      where: '"host" = ''blackpearl'' and time > now() - 5m'
      value_template: "{{ value | round() }}"
      measurement: '"mem"'
      field: '"used_percent"'
      database: server_metrics
    - name: Black Pearl Disk Used
      unit_of_measurement: "%"
      group_function: last
      where: '"host" = ''blackpearl'' and time > now() - 5m'
      value_template: "{{ value | round() }}"
      measurement: '"disk"'
      field: '"used_percent"'
      database: server_metrics
